enum LotteryEnum {
    ADA_KOTIPATHI,
    DHANA_NIDHANAYA,
    HADAHANA,
    JAYODHA,
    LAGNA_WASANA,
    MAHAJANA,
    SASIRI,
    SUPER_BALL,
    ADA_SAMPATHA,
    GOVISETHA,
    JAYA,
    KAPRUKA,
    MEGA_POWER,
    SHANIDA,
    SUPIRI_DHANA_SAMPATHA,
}

export default LotteryEnum;